name: Deploy OnyxGraph Screen

on:
  push:
    branches:
      - main   # change if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      # 1. Checkout latest code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Install dependencies
      - name: Install Dependencies
        run: npm ci

      # 3. Build project
      - name: Build Project
        run: npm run build

      # 4. Prepare OnyxGraph folder
      - name: Prepare OnyxGraph folder
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo mkdir -p /var/www/html/TV_Screens/OnyxGraph
            sudo chown -R ubuntu:ubuntu /var/www/html/TV_Screens/OnyxGraph

      # 5. Upload new build
      - name: Upload build files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist/*"
          target: "/var/www/html/TV_Screens/OnyxGraph"
          strip_components: 1

      # 6. Fix permissions
      - name: Set permissions
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo find /var/www/html/TV_Screens/OnyxGraph -type d -exec chmod 755 {} \;
            sudo find /var/www/html/TV_Screens/OnyxGraph -type f -exec chmod 644 {} \;

      # 7. Reload Nginx
      - name: Reload Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl reload nginx
